helm_deploy/values-dev.yaml

DCS-1098 fix hostname

---

src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/MovementService.kt

(Don't try to read an infinite stream into a list)

DCS-1165 Fix data generator

---

src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/Movement.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/basm/BasmService.kt

This won't always be provided by BaSM

DCS-1165 Making PNC optional

---

README.md
src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/TemporaryAbsence.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/prison/PrisonService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/resources/PrisonResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/resources/TemporaryAbsencesResource.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/resource/IncomingMovesResourceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/resource/PrisonResourceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/resource/TemporaryAbsencesResourceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/utils/LoadJsonHelper.kt
src/test/resources/uk/gov/justice/digital/hmpps/welcometoprison/resource/temporaryAbsence.json

endpoint return stubbed data for temporary absences

DCS-1196 new prison/temporary-absences/{agencyId}   endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/prison/PrisonRegisterClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/prison/PrisonService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/resources/PrisonResource.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/prison/PrisonRegisterClientTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/resource/PrisonResourceTest.kt

Return prison name as 'description'
Fix PrisonResourceTest

DCS-1255: move to do prison lookup using prison registry

---

src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/arrival/Arrival.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/basm/Model.kt

✨DCS-1336: Add Trans gender from BaSM

---

src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/prison/Name.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/basm/BasmServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/basm/BasmTestData.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/prison/NameTest.kt
src/test/resources/uk/gov/justice/digital/hmpps/welcometoprison/integration/move.json
src/test/resources/uk/gov/justice/digital/hmpps/welcometoprison/integration/moves.json
src/test/resources/uk/gov/justice/digital/hmpps/welcometoprison/resource/arrival.json
src/test/resources/uk/gov/justice/digital/hmpps/welcometoprison/resource/arrivals.json

example output in postman. See Alishony and Nancer rather than alishony and nancer

DCS- 1365 WPIP-api capitalise prisoner names

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/prison/PrisonApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/prison/PrisonService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/prison/TemporaryAbsence.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/integration/PrisonApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/prison/PrisonApiClientTest.kt
src/test/resources/uk/gov/justice/digital/hmpps/welcometoprison/resource/temporaryAbsence.json

✨DCS-1168: Add real data to temporary absence endpoint

---

build.gradle.kts
src/main/resources/application.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/arrivals/confirmedarrival/ConfirmedArrivalRepositoryTest.kt
src/test/resources/application-h2flyway.yml

update DB and fix breaking tests

DCS-1387 update h2 database

---

src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/arrivals/ValidImprisonmentStatusAndMovementReasons.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/resource/ImprisonmentReasonsResourceTest.kt

DCS-1363 change to imprisonment status descriptions

---

src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/arrivals/Arrival.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/basm/BasmService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/arrivals/ArrivalsServiceConfirmArrivalTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/arrivals/ArrivalsServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/arrivals/confirmedarrival/ConfirmedArrivalServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/basm/BasmServiceTest.kt

Going to push this in via the frontend to cater setting this for both expected and unexpected arrivals

DCS-1481 Adding fromLocationId

---

src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/prison/prisonersearch/PrisonerSearchService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/prison/prisonersearch/SearchByNameAndDateOfBirth.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/prison/prisonersearch/request/MatchPrisonersRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/resources/MatchPrisonersResource.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/resource/MatchPrisonersResourceTest.kt

supporting searching on a minimum of the following:
* Prison number
* Pnc number
* Last name and dob (with optional first name)

DCS-1534 Supporting search scenarios

---

.circleci/config.yml
gradle/wrapper/gradle-wrapper.properties

**Note: already using the latest helm charts for generic-service and prometheus alerts**

DCS-1548 update gradle and circle orb

---

src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/arrivals/RecentArrival.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/resources/RecentArrivalsResource.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/arrivals/RecentArrivalsServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/resource/RecentArrivalsResourceTest.kt

Also make requests without page info return everything

DCS-1604 Fixing sorting 

---

src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/arrivals/ValidImprisonmentStatusAndMovementReasons.kt

DCS-1633 reordered the list of the reasons for which a prisoner 

---

.trivyignore
build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/prison/temporaryabsences/ConfirmTemporaryAbsenceRequest.kt

DCS-1866 Bumping gradle plugin

---

.trivyignore
build.gradle.kts

DCS-1891: 🤖 Bump gradle-spring-boot version to 4.5.5

DCS-1891: 🤖 Bump gradle-spring-boot version to 4.5.5

---

build.gradle.kts

DCS-1905: 🤖 Bump gradle-spring-boot version to 4.5.7

DCS-1905: 🤖 Bump gradle-spring-boot version to 4.5.7

---

.trivyignore
build.gradle.kts

DCS-1920: 🤖 Bump gradle-spring-boot version to 4.6.0

DCS-1920: 🤖 Bump gradle-spring-boot version to 4.6.0

---

src/main/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/arrivals/ValidImprisonmentStatusAndMovementReasons.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/resource/ImprisonmentReasonsResourceTest.kt

*Remove transfer from another establishment reason

DCS-2086 Amend imprisonment reason list

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/config/ResourceServerConfiguration.kt

update as per this
https://plugins.gradle.org/plugin/uk.gov.justice.hmpps.gradle-spring-boot

MAP-262 update to latest version of spring-boot plugin

---

.circleci/config.yml
README.md
build.gradle.kts

See https://dsdmoj.atlassian.net/browse/MAP-1435

Add Kover plugin and configure it for CircleCI

---

build.gradle.kts

[MAP-1558](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?selectedIssue=MAP-1558)
[MAP-1558]: https://dsdmoj.atlassian.net/browse/MAP-1558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-1558 spring boot plugin update

---

build.gradle.kts

[MAP-1569](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?selectedIssue=MAP-1569)
to fix CVE
[MAP-1569]: https://dsdmoj.atlassian.net/browse/MAP-1569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-1569 spring boot plugin update

---

src/test/kotlin/uk/gov/justice/digital/hmpps/welcometoprison/model/prison/prisonersearch/response/MatchPrisonerResponseTest.kt

Tiny PR to upgrade % when for branch coverage of this scenario

MAP-1460 1 MatchPrisonerResponse branch testing upgrade scenarios null Kover
